### ISSUE TITLE
Possible bug with the hashes part of the tutorial

### ISSUE THREAD

**Issue by EduardoBautista** [badboy/try.redis#35]
Here is the screenshot:

https://www.dropbox.com/s/40sw8r2qmbejeh8/Screenshot%202014-12-17%2012.57.10.png?dl=0

**Comment by badboy** [comment]
Sorry for getting back so late, this issue somehow got lost.
I don't see any error, you simply missed the step setting `user:1001` using `HMSET` before getting back the data again
