### ISSUE TITLE
Please update version to support new commands

### ISSUE THREAD

**Issue by twidi** [badboy/try.redis#36]
Hi

Thanks for the tool, useful.

Do you think it would be possible to update the redis server on `try.redis.io` to a more recent version?

For example `ZRANGEBYLEX` and friends are missing :(

Thanks in advance

**Comment by badboy** [comment]
Will do that this weekend, thanks for the reminder :)

**Comment by badboy** [comment]
`*LEX` commands are now supported by try.redis. :)
