### ISSUE TITLE
To show navigation elements to see a learning progress

### ISSUE THREAD

**Issue by IgorBabalich** [badboy/try.redis#41]
Would be great to see where the user is, what is the studying progress, please,
so it will be possible how much completed and how much more to learn.

**Comment by somombo** [comment]
I second this.. I'm discouraged to go through the tutorial because I dunno... It might take forever!

**Comment by loganhuskins** [comment]
@badboy I can implement this if you want.

**Comment by badboy** [comment]
Feel free to do so. I won't have the time to work on it.
