### ISSUE TITLE
LRANGE results are a bit confusing

### ISSUE THREAD

**Issue by styfle** [badboy/try.redis#43]
This is my first time using redis, thanks for this demo :100: 

The `LRANGE` command seems like the index starts at 0, not 1. However, the output shows the first item at 1.

## Current behavior
```
    LRANGE friends 0 -1 => 1) "Sam", 2) "Alice", 3) "Bob"
    LRANGE friends 0 1 => 1) "Sam", 2) "Alice"
    LRANGE friends 1 2 => 1) "Alice", 2) "Bob"
```

## Expected behavior
```
    LRANGE friends 0 -1 => 0) "Sam", 1) "Alice", 2) "Bob"
    LRANGE friends 0 1 => 0) "Sam", 1) "Alice"
    LRANGE friends 1 2 => 0) "Alice", 1) "Bob"
```

In my opinion, the output should start at 0.

**Comment by badboy** [comment]
That's the way `redis-cli` chose to display it and I'd like to mimick it as close as possible.
