### ISSUE TITLE
Is this live?

### ISSUE THREAD

**Issue by merriam** [badboy/try.redis#45]
This is still the first hit for "reddis tutorial" and it still runs.   I noticed a few problems in running the tutorial such as missing or incorrect help files.   If the project is still 'live-ish', I'll happy contribute patches.  If it's abandoned, that's fine as well.

**Comment by badboy** [comment]
Hey Merriam. It is still live-ish. I don't have much time to work on it, but I will happily merge (and deploy) improvements to the tutorial and help. Depending on how large changes are it might take time for me to review though.

**Comment by merriam** [comment]
Thanks.  I'm going a bit slow.  It's a case of scratching an itch and finding out it itches because of broken bones. :)   I'll update the doc files first.
