### ISSUE TITLE
Time to upgrade Redis again

### ISSUE THREAD

**Issue by navinpai** [badboy/try.redis#46]
Hey,
Just noticed that the version of redis running seems to be out of date again. The TOUCH command has been there [since release 3.2.1](http://redis.io/commands/touch) (current release is 3.2.4) so I'm guessing you're running something older.

![screenshot](http://i.imgur.com/XepnRCw.png)

Would be great if you could upgrade your version! Thanks for maintaining this 👍

**Comment by renaudbedard** [comment]
It also doesn't support the GEO commands from 3.2.0, which would be useful to test!

**Comment by badboy** [comment]
try.redis is effectively unmaintained since March. I won't upgrade it, but keep it running in its current state only.
