### ISSUE TITLE
Use try.redis in iFrame

### ISSUE THREAD

**Issue by JenningLang** [badboy/try.redis#47]
Hi, I tried to embed "http://try.redis.io/" in a iFrame tag, but it is prevented because 

    it set 'X-Frame-Options' to 'SAMEORIGIN' 

Could anybody give me some kindly help about this?

**Comment by badboy** [comment]
Where are you trying to embed it?
I run try.redis as a free service on limited resources. 
I'd prefer if you embed your own instance if you want to use it from your site.
